# Generated by Django 3.1 on 2021-08-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210816_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
